lauguage: ruby
rvm:
  - 2.1.0
before_install: wget --no-check-certificate https://dl.bintray.com/mitchellh/packer/packer_0.7.5_linux_amd64.zip
  && unzip -d packer packer_0.7.5_linux_amd64.zip
before_script: export PATH=$PATH:$PWD/packer
script:
  - PATH=$(pwd)/bin:$PATH bundle exec rake
